"""create_jobs_tables

Revision ID: 151a105ef8d5
Revises: 
Create Date: 2026-08-21 16:13:27.420218

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '151a105ef8d5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discovery_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_identifier', sa.String(length=256), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('candidates_discovered', sa.Integer(), nullable=True),
    sa.Column('pages_fetched', sa.Integer(), nullable=True),
    sa.Column('jobs_new', sa.Integer(), nullable=True),
    sa.Column('jobs_updated', sa.Integer(), nullable=True),
    sa.Column('jobs_duplicate', sa.Integer(), nullable=True),
    sa.Column('jobs_failed', sa.Integer(), nullable=True),
    sa.Column('errors', sa.JSON(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discovery_runs_source'), 'discovery_runs', ['source'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('canonical_key', sa.String(length=128), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_job_id', sa.String(length=256), nullable=False),
    sa.Column('company', sa.String(length=256), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('original_title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('original_description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=256), nullable=True),
    sa.Column('locations', sa.JSON(), nullable=True),
    sa.Column('remote_type', sa.String(length=32), nullable=True),
    sa.Column('employment_type', sa.String(length=32), nullable=True),
    sa.Column('experience_level', sa.String(length=32), nullable=True),
    sa.Column('education_requirements', sa.JSON(), nullable=True),
    sa.Column('graduation_requirement', sa.JSON(), nullable=True),
    sa.Column('graduation_year_requirement', sa.Integer(), nullable=True),
    sa.Column('required_skills', sa.JSON(), nullable=True),
    sa.Column('preferred_skills', sa.JSON(), nullable=True),
    sa.Column('technologies', sa.JSON(), nullable=True),
    sa.Column('responsibilities', sa.JSON(), nullable=True),
    sa.Column('qualifications', sa.JSON(), nullable=True),
    sa.Column('salary_text', sa.String(length=256), nullable=True),
    sa.Column('application_url', sa.String(length=1024), nullable=True),
    sa.Column('source_url', sa.String(length=1024), nullable=False),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('processing_status', sa.String(length=32), nullable=False),
    sa.Column('job_status', sa.String(length=32), nullable=False),
    sa.Column('extraction_metadata', sa.JSON(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_job_id', name='uq_source_job')
    )
    op.create_index(op.f('ix_jobs_canonical_key'), 'jobs', ['canonical_key'], unique=True)
    op.create_index(op.f('ix_jobs_company'), 'jobs', ['company'], unique=False)
    op.create_index(op.f('ix_jobs_content_hash'), 'jobs', ['content_hash'], unique=False)
    op.create_index(op.f('ix_jobs_employment_type'), 'jobs', ['employment_type'], unique=False)
    op.create_index(op.f('ix_jobs_job_status'), 'jobs', ['job_status'], unique=False)
    op.create_index(op.f('ix_jobs_location'), 'jobs', ['location'], unique=False)
    op.create_index(op.f('ix_jobs_processing_status'), 'jobs', ['processing_status'], unique=False)
    op.create_index(op.f('ix_jobs_remote_type'), 'jobs', ['remote_type'], unique=False)
    op.create_index('ix_jobs_source_source_job_id', 'jobs', ['source', 'source_job_id'], unique=False)
    op.create_table('job_source_references',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_job_id', sa.String(length=256), nullable=False),
    sa.Column('source_url', sa.String(length=1024), nullable=False),
    sa.Column('application_url', sa.String(length=1024), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_job_id', name='uq_source_ref')
    )
    op.create_index(op.f('ix_job_source_references_job_id'), 'job_source_references', ['job_id'], unique=False)
    op.create_table('job_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('changes_summary', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_versions_job_id'), 'job_versions', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_versions_job_id'), table_name='job_versions')
    op.drop_table('job_versions')
    op.drop_index(op.f('ix_job_source_references_job_id'), table_name='job_source_references')
    op.drop_table('job_source_references')
    op.drop_index('ix_jobs_source_source_job_id', table_name='jobs')
    op.drop_index(op.f('ix_jobs_remote_type'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_processing_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_location'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_job_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_employment_type'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_content_hash'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_company'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_canonical_key'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_discovery_runs_source'), table_name='discovery_runs')
    op.drop_table('discovery_runs')
    # ### end Alembic commands ###
