"""create_phase3_tables

Revision ID: b11ea16cb71f
Revises: 151a105ef8d5
Create Date: 2026-08-22 15:39:30.803835

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b11ea16cb71f'
down_revision: Union[str, None] = '151a105ef8d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_policies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('weights', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    op.create_table('match_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('policy_version', sa.String(length=32), nullable=False),
    sa.Column('engine_version', sa.String(length=32), nullable=False),
    sa.Column('career_brain_version', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('jobs_processed', sa.Integer(), nullable=True),
    sa.Column('trigger', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_matches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('eligibility_status', sa.String(length=32), nullable=False),
    sa.Column('eligibility_reasons', sa.JSON(), nullable=True),
    sa.Column('blocking_reasons', sa.JSON(), nullable=True),
    sa.Column('fit_score', sa.Integer(), nullable=False),
    sa.Column('priority', sa.String(length=32), nullable=False),
    sa.Column('match_type', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.String(length=32), nullable=False),
    sa.Column('strengths', sa.JSON(), nullable=True),
    sa.Column('gaps', sa.JSON(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['match_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_matches_job_id'), 'job_matches', ['job_id'], unique=False)
    op.create_index('ix_job_matches_job_run', 'job_matches', ['job_id', 'run_id'], unique=False)
    op.create_index(op.f('ix_job_matches_priority'), 'job_matches', ['priority'], unique=False)
    op.create_table('requirement_assessments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_match_id', sa.String(length=36), nullable=False),
    sa.Column('requirement_name', sa.String(length=128), nullable=False),
    sa.Column('requirement_category', sa.String(length=32), nullable=False),
    sa.Column('requirement_strictness', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('evidence_strength', sa.String(length=32), nullable=False),
    sa.Column('evidence_references', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.String(length=32), nullable=False),
    sa.Column('impact', sa.String(length=128), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['job_match_id'], ['job_matches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requirement_assessments_job_match_id'), 'requirement_assessments', ['job_match_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_requirement_assessments_job_match_id'), table_name='requirement_assessments')
    op.drop_table('requirement_assessments')
    op.drop_index(op.f('ix_job_matches_priority'), table_name='job_matches')
    op.drop_index('ix_job_matches_job_run', table_name='job_matches')
    op.drop_index(op.f('ix_job_matches_job_id'), table_name='job_matches')
    op.drop_table('job_matches')
    op.drop_table('match_runs')
    op.drop_table('match_policies')
    # ### end Alembic commands ###
