from enum import Enum

class RequirementCategory(str, Enum):
    ELIGIBILITY = "ELIGIBILITY"
    EDUCATION = "EDUCATION"
    TECHNICAL_SKILL = "TECHNICAL_SKILL"
    DOMAIN_KNOWLEDGE = "DOMAIN_KNOWLEDGE"
    EXPERIENCE = "EXPERIENCE"
    CERTIFICATION = "CERTIFICATION"
    WORK_AUTHORIZATION = "WORK_AUTHORIZATION"
    LOCATION = "LOCATION"
    RESPONSIBILITY = "RESPONSIBILITY"
    BEHAVIORAL = "BEHAVIORAL"
    PREFERENCE = "PREFERENCE"
    UNKNOWN = "UNKNOWN"

class Strictness(str, Enum):
    HARD = "HARD"
    REQUIRED = "REQUIRED"
    PREFERRED = "PREFERRED"
    NICE_TO_HAVE = "NICE_TO_HAVE"
    SIGNAL = "SIGNAL"
    UNKNOWN = "UNKNOWN"

class MatchStatus(str, Enum):
    MATCHED = "MATCHED"
    PARTIAL = "PARTIAL"
    MISSING = "MISSING"
    UNKNOWN = "UNKNOWN"
    NOT_APPLICABLE = "NOT_APPLICABLE"

class EvidenceStrength(str, Enum):
    DIRECT_VERIFIED = "DIRECT_VERIFIED"
    STRONG_DEMONSTRATED = "STRONG_DEMONSTRATED"
    SUPPORTING = "SUPPORTING"
    INDIRECT = "INDIRECT"
    ADJACENT = "ADJACENT"
    NONE = "NONE"

class ConfidenceLevel(str, Enum):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    UNKNOWN = "UNKNOWN"

class EligibilityStatus(str, Enum):
    ELIGIBLE = "ELIGIBLE"
    INELIGIBLE = "INELIGIBLE"
    UNCERTAIN = "UNCERTAIN"

class MatchType(str, Enum):
    CORE_MATCH = "CORE_MATCH"
    STRETCH_MATCH = "STRETCH_MATCH"
    POOR_MATCH = "POOR_MATCH"
    UNKNOWN = "UNKNOWN"
